# Generated by Django 6.0.2 on 2026-02-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='numero',
            new_name='numero_registro',
        ),
    ]
