FROM node:20-slim AS deps
WORKDIR /app/src
COPY ./src/package.json ./src/package-lock.json ./
RUN npm ci

FROM node:20-slim AS builder
WORKDIR /app/src
COPY --from=deps /app/src/node_modules ./node_modules
COPY ./src ./
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app/src
ENV NODE_ENV=production
COPY --from=builder /app/src/.next ./.next
COPY --from=builder /app/src/public ./public
COPY --from=builder /app/src/package.json ./package.json
COPY --from=builder /app/src/package-lock.json ./package-lock.json
COPY --from=builder /app/src/next.config.mjs ./next.config.mjs
RUN npm ci --omit=dev

EXPOSE 3000

CMD ["npm", "run", "start"]
