name: Build and Push Docker Images

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t budke/gestor-servicos-backend:latest -f src/backend/Dockerfile.prod src/backend
      - run: docker push budke/gestor-servicos-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t budke/gestor-servicos-frontend:latest -f src/frontend/Dockerfile.prod src/frontend
      - run: docker push budke/gestor-servicos-frontend:latest
